# Generated by Django 5.1.3 on 2024-11-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='combo_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='combo_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='address_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='address_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
