# Generated by Django 5.1.3 on 2024-11-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0004_alter_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombo',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='delivery_app.store'),
        ),
    ]
