# Generated by Django 5.1.3 on 2024-11-26 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_alter_productcombo_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereview',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_review', to='delivery_app.store'),
        ),
    ]
